<a href="https://colab.research.google.com/github/sindhura-nk/Artificial-Intelligence-1446/blob/main/MultiClass_Classification_with_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Connect to T4 GPU before proceeding
from warnings import filterwarnings
filterwarnings('ignore')

In [1]:
import pandas as pd
df = pd.read_csv(r'https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/mobile_train%20(1).csv')
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [2]:
df['price_range'].unique()

array([1, 2, 3, 0])

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [4]:
df.isna().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [5]:
df.shape

(2000, 21)

In [7]:
df.duplicated().sum()

np.int64(0)

## Separate X and Y Features

In [8]:
X = df.drop(columns='price_range')
Y = df[['price_range']]

In [9]:
X.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2   2         20       756  2549     9     7         19   
1        136        3   6        905      1988  2631    17     3          7   
2        145        5   6       1263      1716  2603    11     2          9   
3        131        6   9       1216      1786  2769    16     8         11   
4        141        2  14       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  
0        0             0     1  
1        1             1     0  
2        1             1     0  
3        1             0     0  
4        1             1     0

In [10]:
Y.head()

price_range
0            1
1            2
2            2
3            2
4            1

## Data cleaning and data preprocessing

In [12]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler


num_pipe = make_pipeline(
    SimpleImputer(strategy='median'),
    StandardScaler()
).set_output(transform='pandas')


X_pre = num_pipe.fit_transform(X)
X_pre

battery_power      blue  clock_speed  dual_sim        fc    four_g  \
0         -0.902597 -0.990050     0.830779 -1.019184 -0.762495 -1.043966   
1         -0.495139  1.010051    -1.253064  0.981177 -0.992890  0.957886   
2         -1.537686  1.010051    -1.253064  0.981177 -0.532099  0.957886   
3         -1.419319  1.010051     1.198517 -1.019184 -0.992890 -1.043966   
4          1.325906  1.010051    -0.395011 -1.019184  2.002254  0.957886   
...             ...       ...          ...       ...       ...       ...   
1995      -1.011860  1.010051    -1.253064  0.981177 -0.992890  0.957886   
1996       1.653694  1.010051     1.321096  0.981177 -0.992890 -1.043966   
1997       1.530773 -0.990050    -0.762748  0.981177 -0.762495  0.957886   
1998       0.622527 -0.990050    -0.762748 -1.019184 -0.071307  0.957886   
1999      -1.658331  1.010051     0.585621  0.981177  0.159088  0.957886   

      int_memory     m_dep  mobile_wt   n_cores        pc  px_height  \
0      -1.380644  0.340740   1.349249 -1.101971 -1.305750  -1.408949   
1       1.155024  0.687548  -0.120059 -0.664768 -0.645989   0.585778   
2       0.493546  1.381165   0.134244  0.209639 -0.645989   1.392684   
3      -1.215274  1.034357  -0.261339  0.646842 -0.151168   1.286750   
4       0.658915  0.340740   0.021220 -1.101971  0.673534   1.268718   
...          ...       ...        ...       ...       ...        ...   
1995   -1.656260  1.034357  -0.967737  0.646842  0.673534   1.300273   
1996    0.383299 -1.046495   1.320993 -0.227564 -1.140810   0.608317   
1997    0.217930  0.687548  -0.911225  1.521249 -1.140810   0.502383   
1998    0.769162 -1.393304   0.134244  0.209639 -0.810929  -0.696707   
1999    0.714039  1.381165   0.784130  0.646842  1.003414  -0.365380   

      px_width       ram      sc_h      sc_w  talk_time   three_g  \
0    -1.146784  0.391703 -0.784983  0.283103   1.462493 -1.786861   
1     1.704465  0.467317  1.114266 -0.635317  -0.734267  0.559641   
2     1.074968  0.441498 -0.310171 -0.864922  -0.368140  0.559641   
3     1.236971  0.594569  0.876859  0.512708  -0.002014  0.559641   
4    -0.091452 -0.657666 -1.022389 -0.864922   0.730240  0.559641   
...        ...       ...       ...       ...        ...       ...   
1995  1.477661 -1.342799  0.164641 -0.405712   1.462493  0.559641   
1996  1.651235 -0.085031 -0.310171  0.971917   0.913303  0.559641   
1997  0.880565  0.860139 -0.784983 -1.094526  -1.100394  0.559641   
1998 -1.345816 -1.157454  1.351672  0.971917   1.462493  0.559641   
1999 -1.151413  1.655004  1.589078 -0.405712  -1.649584  0.559641   

      touch_screen      wifi  
0        -1.006018  0.986097  
1         0.994018 -1.014099  
2         0.994018 -1.014099  
3        -1.006018 -1.014099  
4         0.994018 -1.014099  
...            ...       ...  
1995      0.994018 -1.014099  
1996      0.994018  0.986097  
1997      0.994018 -1.014099  
1998      0.994018  0.986097  
1999      0.994018  0.986097  

[2000 rows x 20 columns]

## Split the data into training and testing

In [13]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X_pre,Y,train_size=0.80,random_state=42)
print(xtrain.shape,xtest.shape,ytrain.shape,ytest.shape,sep='\t')

(1600, 20)	(400, 20)	(1600, 1)	(400, 1)


## Convert y data into categorical data- preprocess the Y daTA

In [21]:
ytrain['price_range'].unique()

array([1, 2, 0, 3])

In [22]:
from keras.utils import to_categorical
ytrain_cat = to_categorical(ytrain)
ytest_cat = to_categorical(ytest)

In [23]:
ytrain_cat[:1]

array([[0., 1., 0., 0.]])

In [24]:
ytrain_cat.shape

(1600, 4)

## Model building

In [14]:
from keras.models import Sequential
from keras.layers import Input,Dense

In [15]:
xtrain.shape[1]

20

In [25]:
ytrain_cat.shape

(1600, 4)

In [31]:
model = Sequential()

# Add the input layer
model.add(Input(shape=(xtrain.shape[1],)))

# Add the Dense layer-Hidden layer1
model.add(Dense(units=32,activation='relu'))

# Add the Dense layer-Hidden layer2
model.add(Dense(units=16,activation='relu'))

# Add the output layer
model.add(Dense(units=ytrain_cat.shape[1],activation='softmax'))

In [32]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 32)             │           672 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 4)              │            68 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,268 (4.95 KB)

 Trainable params: 1,268 (4.95 KB)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [34]:
nn = model.fit(xtrain,ytrain_cat,epochs=25,validation_split=0.25)

Epoch 1/25
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.2337 - loss: 1.4781 - val_accuracy: 0.3200 - val_loss: 1.3539
Epoch 2/25
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3492 - loss: 1.3103 - val_accuracy: 0.4175 - val_loss: 1.2706
Epoch 3/25
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4280 - loss: 1.2365 - val_accuracy: 0.4375 - val_loss: 1.1803
Epoch 4/25
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5405 - loss: 1.1048 - val_accuracy: 0.4975 - val_loss: 1.0784
Epoch 5/25
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6085 - loss: 0.9918 - val_accuracy: 0.5475 - val_loss: 0.9723
Epoch 6/25
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6456 - loss: 0.8968 - val_accuracy: 0.6025 - val_loss: 0.8733
Epoch 7/25
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6640 - loss: 0.7979 - val_accuracy: 0.6450 - val_loss: 0.7842
Epoch 8/25
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6883 - loss: 0.7206 - val_accuracy: 0.7025 - val_loss

## Learning Curve

In [35]:
import matplotlib.pyplot as plt
plt.plot(nn.history['loss'],label ='Training Loss')
plt.plot(nn.history['val_loss'],label='Validation Loss')
plt.legend()
plt.title('Learning Curve')
plt.xlabel('Number of Epochs')
plt.ylabel('Categorical CrossEntropy Loss')
plt.show()

## Evaluate the model

In [37]:
model.evaluate(xtrain,ytrain_cat)

50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9716 - loss: 0.1335


[0.15811580419540405, 0.9593750238418579]

In [38]:
model.evaluate(xtest,ytest_cat)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9227 - loss: 0.2043


[0.2191798985004425, 0.9100000262260437]

## Save the model for final out of sample predictions

In [39]:
model.save('MobilePrice.keras')

## Load the model

In [40]:
from keras.models import load_model
m1 = load_model('/content/MobilePrice.keras')
m1.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 32)             │           672 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 4)              │            68 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,806 (14.87 KB)

 Trainable params: 1,268 (4.95 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,538 (9.92 KB)

ytrain['price_range'].unique(

In [42]:
ytrain['price_range'].unique()

array([1, 2, 0, 3])

In [41]:
ypreds_test = m1.predict(xtest)
ypreds_test[0]

13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step


array([9.6368098e-01, 3.6318820e-02, 2.2066835e-07, 5.9629766e-12],
      dtype=float32)

In [43]:
import numpy as np
final_ypreds_test = np.argmax(ypreds_test,axis=1)
final_ypreds_test[:10]

array([0, 2, 1, 3, 1, 1, 1, 0, 3, 1])

In [45]:
from sklearn.metrics import accuracy_score
ac_sc = accuracy_score(ytest,final_ypreds_test)
ac_sc

0.91

## Check the confusion matrix and classification reports as well

In [50]:
ytest_cat[0]

array([1., 0., 0., 0.])

In [53]:
from sklearn.metrics import classification_report,ConfusionMatrixDisplay
# ConfusionMatrixDisplay.from_estimator(m1,xtest,ytest_cat)
# plt.show()

ValueError: ConfusionMatrixDisplay.from_estimator only supports classifiers

In [52]:
print(classification_report(ytest,final_ypreds_test))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92       105
           1       0.85      0.91      0.88        91
           2       0.89      0.89      0.89        92
           3       0.95      0.93      0.94       112

    accuracy                           0.91       400
   macro avg       0.91      0.91      0.91       400
weighted avg       0.91      0.91      0.91       400



## Out of sample predictions

In [54]:
xnew = pd.read_csv(r'https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/mobile_test%20(1).csv')
xnew.head()

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0   1           1043     1          1.8         1  14       0           5   
1   2            841     1          0.5         1   4       1          61   
2   3           1807     1          2.8         0   1       0          27   
3   4           1546     0          0.5         1  18       1          25   
4   5           1434     0          1.4         0  11       1          49   

   m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0    0.1        193  ...  16        226      1412  3476    12     7   
1    0.8        191  ...  12        746       857  3895     6     0   
2    0.9        186  ...   4       1270      1366  2396    17    10   
3    0.5         96  ...  20        295      1752  3893    10     0   
4    0.5        108  ...  18        749       810  1773    15     8   

   talk_time  three_g  touch_screen  wifi  
0          2        0             1     0  
1          7        1             0     0  
2         10        0             1     1  
3          7        1             1     0  
4          7        1             0     1  

[5 rows x 21 columns]

In [55]:
xnew2 = xnew.drop(columns='id')
xnew_pre = num_pipe.transform(xnew2)
final_preds = m1.predict(xnew_pre)
final_preds[:5]

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


array([[8.7802071e-10, 3.1438004e-04, 7.7302063e-01, 2.2666505e-01],
       [1.7503702e-08, 8.4051595e-04, 2.6668948e-01, 7.3246998e-01],
       [1.5808526e-08, 1.1145067e-03, 7.0300484e-01, 2.9588071e-01],
       [1.6157396e-12, 2.8897557e-06, 5.5609727e-03, 9.9443614e-01],
       [8.2755998e-02, 8.8370603e-01, 3.3426110e-02, 1.1191798e-04]],
      dtype=float32)

In [56]:
final_preds2 = np.argmax(final_preds,axis=1)
final_preds2[:10]

array([2, 3, 2, 3, 1, 3, 3, 1, 3, 0])

In [57]:
xnew['Mobile Price Range Predictions']=final_preds2
xnew.to_csv('Predictions.csv',index=False)